<div id="marche-dialog-elimina" class="marche elimina dialog main">
    <?php
    if($this->canDelete)
    {
    ?>
    <div id="marche-dialog-elimina-testo" class="elimina-testo">
        <p>Attenzione: hai scelto di eliminare la marca "<?php echo $this->marca['Nome']; ?>".</p>
        <p>Confermi l'operazione?</p>
        <div id="marche-dialog-elimina-form" class="elimina-form">
        <?php
            echo $this->form;
            echo $this->formAjaxify($this->form->getAttrib('id'));
        ?>
        </div>
    </div>
    <?php
    }
    else
    {
    ?>
    <div id="marche-dialog-elimina-testo" class="elimina-testo">
        <p>Attenzione: La marca "<?php echo $this->marca['Nome']; ?>" ha degli articoli assegnati, per cui non è possibile eliminarla.</p>
    </div>
    <?php
    }
    ?>
</div>