<div id="marche-edita" class="marche edita page ui-widget-content ui-corner-all">
    <div id="marche-edita-titolo" class="edita-titolo">
        Edita <?php echo $this->config->language->brandNameSing." \"".$this->marca['Nome']; ?>"
    </div>
    <div id="marche-edita-form" class="edita-form">
<?php
    echo $this->form;
    echo $this->formAjaxify($this->form->getAttrib('id'));
?>
    </div>
</div>
<script type="text/javascript">
    function LinkSito()
    {
            if($('#Sito').val().replace('http://','').length)
            {
                uri = $('#Sito').val();
                if(uri.substring(0,4) != 'http')
                    uri = 'http://' + uri;
                if($('#linkSito').length)
                    $('#linkSito').attr('href',uri);
                else
                    $('#Sito').after(' <a id="linkSito" target="_blank" href="' + uri + '">Vai a</a>');
            }
            else
            {
                $('#linkSito').remove();
            }
    }
    $('#Sito').keyup(LinkSito);
    LinkSito();
</script>