<p>Gentile <?php echo $this->nome.' '.$this->cognome; ?>,</p>
<p>Ci è pervenuta una sua richiesta di nuova password per il nostro negozio online.</p>
<p>
    Per ottenere una nuova password, inserisca il seguente codice di conferma quando richiesto:
    <em><?php echo $this->confirmationCode ?></em>,
    o in alternativa visiti direttamente l'indirizzo
    <a href='<?php echo $this->serverUrl().$this->url(array('module' => 'user', 'controller' => 'login', 'action' => 'lostPassword')).'?email='.$this->Email.'&code='.$this->confirmationCode; ?>'>
        <?php echo $this->serverUrl().$this->url(array('module' => 'user', 'controller' => 'login', 'action' => 'lostPassword')).'?email='.$this->Email.'&code='.$this->confirmationCode; ?>
    </a>
</p>
<p>Le ricordiamo inoltre che il suo nome utente per l'accesso al nostro negozio è: <?php echo $this->username; ?></p>
<p>Se non ha effettuato alcuna richiesta di nuova password, la preghiamo di ignorare questa email.</p>