<div id="login-container" class="ui-corner-all ui-widget-content">
    <div id="login-logo">
        <img id="login-imglogo" title="AddiXi" alt="AddiXi" src="/css/images/AddiXi.png"/>
    </div>
    <div id="login-area">
        Area di Amministrazione
    </div>
    <div id="login-text">
        Inserisci Nome Utente e Password per l'accesso
    </div>
    <div id="login-form">
        <?php
            if($this->datiErrati)
            {
        ?>
            <div id="login-errors" class="errors">
                Nome Utente o Password errati
            </div>
        <?php
            }
            echo $this->form;
        ?>
    </div>
    <div id="login-links">
        <a href="<?php echo $this->url(array('module' => 'frontend', 'controller' => 'index', 'action' => 'index')); ?>">Vai alla homepage del sito</a>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $("#login").button();
    });
</script>