<div id="categorie-aggiungi" class="categorie aggiungi page ui-widget-content ui-corner-all">
    <div id="categorie-aggiungi-titolo" class="aggiungi-titolo">
    <?php
    	if(isset($this->categoriaPadre))
    	{
    ?>
    		Aggiungi Sottocategoria di:
    <?php
    	echo $this->categoriaPadre->getNome();
    	}
    	else
    	{ 
    ?>
        	Aggiungi Categoria
    <?php
    	} 
    ?>
    </div>
    <div id="categorie-aggiungi-form" class="aggiungi-form">
        <?php
            echo $this->form;
            echo $this->formAjaxify($this->form->getAttrib('id'),'Categoria',null,'Categoria',$this->url(array('controller' => 'categorie', 'action' => 'getSelectOptions')));
        ?>
    </div>
</div>
<?php echo $this->CKEditor(); ?>