<?php
    if($this->wrongCode)
    {
?>
        Spiacente, il codice di conferma specificato è errato
<?php
    }
    if($this->showForm)
    {
?>
        Per ottenere una nuova password è necessario inserire il condice di conferma che le è stato inviato all'indirizzo email indicato
<?php
        echo $this->form;
    }
    else if($this->newPassword)
    {
?>
        La sua nuova password è: <b><?php echo $this->newPassword ?></b>
<?php
    }
    else if($this->noMail)
    {
?>
        Spiacente, non risultano utenti registrati con l'indirizzo email specificato
<?php
    }
?>
<script type="text/javascript">
    $("input[type='submit']").button();
</script>