<h4>E' necessario compilare tutti i campi per poter procedere all'ordine.</h4>
<?php echo $this->form ?>
<script type="text/javascript">
    $("input[type='submit']").button();
    $("input[type='submit']").attr('disabled', 'disabled');
    $("#Condizioni").change(
		function() {
			if($(this).attr('checked'))
				$("input[type='submit']").attr('disabled', '');
			else
			    $("input[type='submit']").attr('disabled', 'disabled');
		}
	);
</script>
